version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=lireddit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
  web:
    container_name: web
    build: .
    command: bash -c "yarn && npx mikro-orm migration:create && yarn dev"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
