version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=lireddit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"

  redis:
    container_name: redis
    image: redis
    command: redis-server --requirepass redis --port 6379
    expose:
      - "6379"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: bash -c "yarn && yarn create:migration && yarn dev"
    volumes:
      - ./backend:/code/backend
      - /code/backend/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: bash -c "yarn && yarn dev"
    volumes:
      - ./frontend:/code/frontend
      - /code/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend